<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'paypal-payment-buttons',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.5.11',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.23-alpha1770651640',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '7.0.3-alpha1770651640',
    ),
    'jetpack-paypal-payments' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-paypal-payments',
      'ver' => '0.6.4-alpha1770651640',
    ),
  ),
);
