<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'paypal-payment-buttons',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.5.11-alpha1753906593',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.2-alpha1753906593',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '6.17.0-alpha1753966628',
    ),
    'jetpack-paypal-payments' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-paypal-payments',
      'ver' => '0.3.1-alpha1753906593',
    ),
  ),
);
